### ISSUE TITLE
T10: Fetch Products

### ISSUE THREAD

**Issue by erayerm** [erayerm/ecommerce#22]
- [x] **Fetch products**
    - [x] by **thunk action** and save it in the **product reducer**
    - [x] endpoint “/products“
    - [x] query parameters:
        - [x] category? : optional. you can limit products by sending category id
        - [x] filter?: optional. products can be filtered by the text
        - [x] sort?: optional. products can be sorted by the fields “price:asc”, “price:desc” , “rating:asc”, “rating:desc”
- [x] you should list products in the UI (shopping page)
- [x] while fetching products data, a loading spinner should be shown on the screen
- [x] in response you will get Object like below:
   ```js{
      total: 185,
      products: [
         { ProductObject1 }, 
         { ProductObject2 }, 
         …
      ]
   }
   ```

**Comment by erayerm** [comment]
2855983 - Commit'i yanlış issue ile ilişkilendirmişim.

**Comment by erayerm** [comment]
> [2855983](https://github.com/erayerm/ecommerce/commit/2855983a82fab11019675100dd3450f52e078090) - Commit'i yanlış issue ile ilişkilendirmişim.

@gokhanozdemir Merhaba, ProductList sayfasında sayfayı refresh'lediğimde -videodaki gibi- önce category parametresinin boş olduğu haliyle axios atılıyor (satır 52) ardından adres çubuğundan gelen veriye göre category'yi güncelleyince (satır 39) bu sefer yeni category ile axios atılıyor ve yeni ürünler geliyor. İlk axios isteğini nasıl iptal edebileceğim hakkında bir fikriniz var mı?

Bahsettiğim kısmın kodları [Product.jsx](https://github.com/erayerm/ecommerce/blob/main/src/components/Products.jsx) içinde.



https://github.com/erayerm/ecommerce/assets/73521213/8a214510-9452-4081-b8e4-22598d695e28

**Comment by erayerm** [comment]
8a2057b - Sorunu burada çözdüm. Ekstra bir state ekleyip params varsa ilk fetch'i yapmamasını sağladım ama ideal bir çözüm mü emin değilim.

**Comment by gokhanozdemir** [comment]
Aslında çözümün bir yerden baya ideale yakın. genderParams'ı üst seviyede useParams ile okuyup mu içeri atıyorsun? Bir de tanımsızlıklar için "" kullanmanın özel bir sebebi var mı? Neden null ya da undefined kullanmadın? @erayerm mesela aynı dosya satır 11. useEffectler aynı anda aynı şeyleri de takip etmemiş o da güzel.
