### ISSUE TITLE
T20: Complete Order

### ISSUE THREAD

**Issue by erayerm** [erayerm/ecommerce#35]
- [x] Create a **GET** request to “**/order**” endpoint to get previous orders of the logged in user.
- [x] List orders in the screen in a proper template

**Comment by erayerm** [comment]
T19'daki gibi ürünü postladığım zaman response olarak "products: [x]" (x rastgele bir sayı) dönüyor.

![Image](https://github.com/erayerm/ecommerce/assets/73521213/f0f28792-cc9e-459b-a633-6f1a65eb7b0e)

Bu task'teki gibi /order'a get attığım zaman alınan ürünlerin datası gelmiyor. Bu task için yalnızca gelen datadaki bilgileri mi yazdırmalıyım yoksa ürünleri gönderirken hata mı yapıyorum? @erhanfirat @gokhanozdemir

![Image](https://github.com/erayerm/ecommerce/assets/73521213/9adfce9d-3efc-4393-b1d6-16480576064c)

**Comment by gokhanozdemir** [comment]
@erayerm backend'de sorun var. Sen orayı `//FIXME: Pending backend fix` diye commentleyip, datayı kendi redux storundaki haliyle tutarak ilerleyebilir misin? @erayerm 

@erhanfirat güncelleyince fişleriz.
