### ISSUE TITLE
T4: Make Responsive

### ISSUE THREAD

**Issue by erayerm** [erayerm/ecommerce#8]
In figma design there are also mobile views. **Mobile views** should be implemented to all pages:
- [x] Home
- [x] Shopping
- [x] Product
- [x] About
- [x] Team
- [x] Contact
- [x] [**CHECK Tailwind responsive solution:**](https://tailwindcss.com/docs/responsive-design)
- [x] [**CHECK Tailwind switch breakpoints min to max responsive solution:**](https://tailwindcss.com/docs/screens#max-width-breakpoints)

**Comment by erayerm** [comment]
4d7c632

**Comment by gokhanozdemir** [comment]
Gözlerim şenlendi :D eline sağlık ^^
